# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='is_loop',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
