# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_convertvidrequestmodel_is_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertvidrequestmodel',
            name='vid_file',
            field=models.FileField(upload_to='uploads/%Y/%m'),
        ),
    ]
