# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20161127_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertvidrequestmodel',
            name='is_loop',
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='caption_position',
            field=models.IntegerField(choices=[(1, 'Top'), (2, 'Middle'), (3, 'Bottom')], default=1),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='loop_mode',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Symmetrical')], default=1),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='quality',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'High'), (3, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='result_file_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='size',
            field=models.IntegerField(choices=[(1, 'Original'), (2, 'Smaller'), (3, 'Bigger')], default=1),
        ),
        migrations.AddField(
            model_name='convertvidrequestmodel',
            name='speed',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Fast'), (3, 'Slow')], default=1),
        ),
    ]
